"""add resource_id to appointment

Revision ID: 1108ac663661
Revises: be04cc952b68
Create Date: 2025-12-22 13:24:55.612851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1108ac663661'
down_revision = 'be04cc952b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointment_resource_id_resource'), 'resource', ['resource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointment_resource_id_resource'), type_='foreignkey')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###
