"""Criar tabela de audit_logs

Revision ID: 126603d4e943
Revises: 36c2545d6e05
Create Date: 2025-12-24 19:28:43.497831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126603d4e943'
down_revision = '36c2545d6e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
