"""add image_url to service

Revision ID: 36c2545d6e05
Revises: 7c9768eb37a7
Create Date: 2025-12-24 11:16:12.493197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c2545d6e05'
down_revision = '7c9768eb37a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
