"""adicionando payment_status

Revision ID: 680cbf0a51c7
Revises: 87f3166ed8da
Create Date: 2025-12-20 11:45:17.223452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680cbf0a51c7'
down_revision = '87f3166ed8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
