"""Add lockout fields to user model

Revision ID: 6c8efca712eb
Revises: 6c1c5b717b5f
Create Date: 2025-12-21 13:16:52.842380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8efca712eb'
down_revision = '6c1c5b717b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
