"""adiciona campos de marketing ao servico

Revision ID: be04cc952b68
Revises: 6c8efca712eb
Create Date: 2025-12-21 16:42:20.709550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be04cc952b68'
down_revision = '6c8efca712eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('indications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contraindications', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_active'))
        batch_op.drop_column('contraindications')
        batch_op.drop_column('indications')
        batch_op.drop_column('benefits')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
