"""Adicionando perfis de usuario

Revision ID: d5604025f23b
Revises: 126603d4e943
Create Date: 2025-12-26 19:55:56.949439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5604025f23b'
down_revision = '126603d4e943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('insurance_plan', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_patient_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profile')),
    sa.UniqueConstraint('cpf', name=op.f('uq_patient_profile_cpf')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profile_user_id'))
    )
    op.create_table('staff_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_reg', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('work_hours', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_staff_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_staff_profile_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_profile')
    op.drop_table('patient_profile')
    # ### end Alembic commands ###
